version: '3'

services:
    app:
        build:
          context: .
          dockerfile: deployment/Dockerfile
        env_file:
            - .env
        ports:
            - "8080:8080"
        depends_on:
            - db
        environment:
            POSTGRES_HOST: db
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        restart: always

    db:
        image: postgres
        container_name: postgres_go
        restart: always
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    db_data:
