
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build Go Project
      run: go build -v ./...

    - name: Install golangci-lint for Linting
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest


    - name: Run golangci-lint
        run: golangci-lint run ./...

    - name: Test Go Project
      run: go test -v ./...


